import QtQuick

QtObject {
    readonly property string appTitle: "Comic Pile"
    readonly property string appWindowTitle: "Comic Pile (Qt Prototype)"
    readonly property string searchPlaceholder: "Search"
    readonly property string inventoryRebuildStatus: "Library Or Database Changed. Rebuilding Inventory..."
    readonly property string settingsSoonLabel: "Settings (soon)"
    readonly property string aboutSoonLabel: "About Comic Pile (soon)"
    readonly property string unknownSeriesLabel: "Unknown series"

    readonly property string interFontPath: "qrc:/qt/qml/ComicPile/assets/fonts/Inter-VariableFont_opsz,wght.ttf"
    readonly property string publisherLogoMarvelComics: "qrc:/qt/qml/ComicPile/assets/ui/logo-marvel-comics-wide.png"
    readonly property string publisherLogoDcComics: "qrc:/qt/qml/ComicPile/assets/ui/logo-dc-comics-round.png"
    readonly property string publisherLogoImageComics: "qrc:/qt/qml/ComicPile/assets/ui/logo-image-comics-tall.png"
    readonly property string publisherLogoDarkHorseComics: "qrc:/qt/qml/ComicPile/assets/ui/logo-dark-horse-studio-tall.png"
    readonly property string publisherLogoBoomStudios: "qrc:/qt/qml/ComicPile/assets/ui/logo-boom-studio-wide.png"
    readonly property string publisherLogoDynamiteEntertainment: "qrc:/qt/qml/ComicPile/assets/ui/logo-dynamite-wide.png"
    readonly property string publisherLogoValiantComics: "qrc:/qt/qml/ComicPile/assets/ui/logo-valiant-comics-tall.png"
    readonly property string publisherLogoAfterShockComics: "qrc:/qt/qml/ComicPile/assets/ui/logo-after-shock-round.png"
    readonly property string publisherLogoAwaStudios: "qrc:/qt/qml/ComicPile/assets/ui/logo-awa-wide.png"
    readonly property string publisherLogoOniPress: "qrc:/qt/qml/ComicPile/assets/ui/logo-oni-press-wide.png"
    readonly property string publisherLogoTopCowProductions: "qrc:/qt/qml/ComicPile/assets/ui/logo-top-cow-productions-standard.png"
    readonly property string publisherLogoIdwPublishing: "qrc:/qt/qml/ComicPile/assets/ui/logo-idw-publishing-round.png"
    readonly property string publisherLogoShueisha: "qrc:/qt/qml/ComicPile/assets/ui/logo-shueisha-standard.png"
    readonly property string publisherLogoArchieComics: "qrc:/qt/qml/ComicPile/assets/ui/logo-archie-comics-wide.png"
    readonly property string publisherLogoAspenComics: "qrc:/qt/qml/ComicPile/assets/ui/logo-aspen-comics-tall.png"
    readonly property string publisherLogoCasterman: "qrc:/qt/qml/ComicPile/assets/ui/logo-casterman-wide.png"
    readonly property string publisherLogoDargaud: "qrc:/qt/qml/ComicPile/assets/ui/logo-dargaud-wide.png"
    readonly property string publisherLogoDelcourt: "qrc:/qt/qml/ComicPile/assets/ui/logo-delcourt-wide.png"
    readonly property string publisherLogoDupuis: "qrc:/qt/qml/ComicPile/assets/ui/logo-dupuis-wide.png"
    readonly property string publisherLogoGlenat: "qrc:/qt/qml/ComicPile/assets/ui/logo-glenat-wide.png"
    readonly property string publisherLogoHakusensha: "qrc:/qt/qml/ComicPile/assets/ui/logo-hakesensha-wide.png"
    readonly property string publisherLogoHumanoids: "qrc:/qt/qml/ComicPile/assets/ui/logo-humanoids-standard.png"
    readonly property string publisherLogoKadokawaCorporation: "qrc:/qt/qml/ComicPile/assets/ui/logo-kadokawa-corporation-standard.png"
    readonly property string publisherLogoKodansha: "qrc:/qt/qml/ComicPile/assets/ui/logo-kodansha-tall.png"
    readonly property string publisherLogoPaniniComics: "qrc:/qt/qml/ComicPile/assets/ui/logo-panini-comics-wide.png"
    readonly property string publisherLogoRebellionDevelopments: "qrc:/qt/qml/ComicPile/assets/ui/logo-rebellion-wide.png"
    readonly property string publisherLogoShogakukan: "qrc:/qt/qml/ComicPile/assets/ui/logo-shogakui-wide.png"
    readonly property string publisherLogoSquareEnix: "qrc:/qt/qml/ComicPile/assets/ui/logo-square-enix-wide.png"
    readonly property string publisherLogoTitanComics: "qrc:/qt/qml/ComicPile/assets/ui/logo-titan-comics-tall.png"
    readonly property string publisherLogoUdonEntertainment: "qrc:/qt/qml/ComicPile/assets/ui/logo-udon-entertainment-tall.png"
    readonly property string publisherLogoVizMedia: "qrc:/qt/qml/ComicPile/assets/ui/logo-viz-media-wide.png"
    readonly property string readerPageArrow: "qrc:/qt/qml/ComicPile/assets/ui/icon-reader-page-arrow.svg"
    readonly property string readerIssueArrow: "qrc:/qt/qml/ComicPile/assets/ui/icon-reader-issue-arrow.svg"
    readonly property string readerBookmarkDecoration: "qrc:/qt/qml/ComicPile/assets/ui/reader-boornark.svg"
    readonly property string sidebarNoiseTexture: "qrc:/qt/qml/ComicPile/assets/textures/sidebar_dither_noise.png"
    readonly property string searchShellFrame: "qrc:/qt/qml/ComicPile/assets/ui/search.png"
    readonly property string searchIcon: "qrc:/qt/qml/ComicPile/assets/icons/search-icon.svg"
    readonly property string appTitleIcon: "qrc:/qt/qml/ComicPile/assets/icons/app-title-16.png"
    readonly property string dropZoneBorder: "qrc:/qt/qml/ComicPile/assets/ui/drop-zone-border.svg"
    readonly property string dropZoneIcon: "qrc:/qt/qml/ComicPile/assets/icons/drop-icon.svg"
    readonly property string dropZoneWhiteIcon: "qrc:/qt/qml/ComicPile/assets/icons/drop-icon-white.svg"
    readonly property string onboardingBackButton: "qrc:/qt/qml/ComicPile/assets/ui/onboarding/back.png"
    readonly property string onboardingNextButton: "qrc:/qt/qml/ComicPile/assets/ui/onboarding/next.png"
    readonly property string onboardingSlash: "qrc:/qt/qml/ComicPile/assets/ui/onboarding/slash.png"
    readonly property string onboardingStep1Bubble: "qrc:/qt/qml/ComicPile/assets/ui/onboarding/step-1.png"
    readonly property string gridTile: "qrc:/qt/qml/ComicPile/assets/ui/grid-tile.png"
    readonly property string heroSlice: "qrc:/qt/qml/ComicPile/assets/ui/hero-9-slice.png"
    readonly property string coverShading: "qrc:/qt/qml/ComicPile/assets/ui/cover-shading.png"
    readonly property string coverDefault: "qrc:/qt/qml/ComicPile/assets/ui/cover-default.png"
    readonly property string coverHover: "qrc:/qt/qml/ComicPile/assets/ui/cover-hover.png"
    readonly property string coverRead: "qrc:/qt/qml/ComicPile/assets/ui/cover-read.png"
    readonly property string coverReadCancel: "qrc:/qt/qml/ComicPile/assets/ui/cover-read-cancel.png"
    readonly property string coverBookmark: "qrc:/qt/qml/ComicPile/assets/ui/cover-bookmark.png"
    readonly property string coverHoverGlow: "qrc:/qt/qml/ComicPile/assets/ui/cover-hover-glow.png"
    readonly property string gridEdgeLeft: "qrc:/qt/qml/ComicPile/assets/ui/grid-edge-left.png"
    readonly property string gridEdgeRight: "qrc:/qt/qml/ComicPile/assets/ui/grid-edge-right.png"
    readonly property string gridEdgeBottom: "qrc:/qt/qml/ComicPile/assets/ui/grid-edge-bottom.png"
    readonly property string gridCornerBottomLeft: "qrc:/qt/qml/ComicPile/assets/ui/grid-corner-bl.png"
    readonly property string gridCornerBottomRight: "qrc:/qt/qml/ComicPile/assets/ui/grid-corner-br.png"
    readonly property string gridNotch: "qrc:/qt/qml/ComicPile/assets/ui/notch.png"
    readonly property string folderClosedIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-folder.png"
    readonly property string folderHoverIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-folder-hover.png"
    readonly property string folderOpenedIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-folder-opened.png"
    readonly property string sidebarBookmarksIdleIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-boormarks-idle.png"
    readonly property string sidebarBookmarksHoverIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-boormarks-hover.png"
    readonly property string sidebarFavoritesIdleIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-favorits-idle.png"
    readonly property string sidebarFavoritesHoverIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-favorits-hover.png"
    readonly property string sidebarLastImportIdleIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-last-import-idle.png"
    readonly property string sidebarLastImportHoverIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-last-import-hover.png"
    readonly property string quickFilterTitleBookmarkIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-title-bookmark.png"
    readonly property string quickFilterTitleFavoriteIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-title-favorit.png"
    readonly property string quickFilterTitleLastImportIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-title-last-import.png"
    readonly property string verticalDotsIcon: "qrc:/qt/qml/ComicPile/assets/icons/3_dots.svg"
    readonly property string copyIcon: "qrc:/qt/qml/ComicPile/assets/icons/copy.svg"
    readonly property string popupInfoIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-popup-info.svg"
    readonly property string readerBookmarkIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-reader-bookmark.svg"
    readonly property string readerFavoritesIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-reader-favorits.svg"
    readonly property string readerDeletePageIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-reader-delete.svg"
    readonly property string readerSettingsIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-reader-settings.svg"
    readonly property string readerCopyIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-reader-copy.svg"
    readonly property string readerMagnifierCursorShadowIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-reader-magnifier-shadow.svg"
    readonly property string readerMangaIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-reader-manga.svg"
    readonly property string readerOnePageIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-reader-one-page.svg"
    readonly property string readerTwoPageIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-reader-two-page.svg"
    readonly property string readerFullScreenIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-reader-full-screen.svg"
    readonly property string readerThemeMoonIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-reader-moon.svg"
    readonly property string readerThemeSunIcon: "qrc:/qt/qml/ComicPile/assets/icons/icon-reader-sun.svg"
    readonly property string pencilLineGrayIcon: "qrc:/qt/qml/ComicPile/assets/icons/pencil-line-gray.svg"
    readonly property string pencilLineWhiteIcon: "qrc:/qt/qml/ComicPile/assets/icons/pencil-line-white.svg"
}
